services:
  db:
    image: postgis/postgis:15-3.3
    platform: linux/amd64
    container_name: braddock_postgis
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./server/database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  postgis_data: